postgres:
	docker run --name postgres17 --network bank-network -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres
createdb:
	docker exec -it postgres17 createdb --username=root --owner=root simplebank
dropdb:
	docker exec -it postgres17 dropdb simplebank
migrateup:
	migrate -path ./db/migration -database "postgresql://root:secret@localhost:5432/simplebank?sslmode=disable" -verbose up
migratedown:
	migrate -path ./db/migration -database "postgresql://root:secret@localhost:5432/simplebank?sslmode=disable" -verbose down
migrateup1:
	migrate -path ./db/migration -database "postgresql://root:secret@localhost:5432/simplebank?sslmode=disable" -verbose up 1 
migratedown1:
	migrate -path ./db/migration -database "postgresql://root:secret@localhost:5432/simplebank?sslmode=disable" -verbose down 1

new_migration:
	migrate create -ext sql -dir db/migration -seq $(name)

sqlc:
	sqlc generate
test:
	go test -v -cover ./...
mock:
	mockgen -destination db/mock/store.go example.com/simplebank/db/sqlc Store

proto:
	rm -f pb/*.go
	rm -f doc/swagger/*.swagger.json
	protoc --proto_path=proto --go_out=pb --go_opt=paths=source_relative \
    --go-grpc_out=pb --go-grpc_opt=paths=source_relative \
	--grpc-gateway_out=pb --grpc-gateway_opt=paths=source_relative \
	--openapiv2_out=doc/swagger --openapiv2_opt=allow_merge=true,merge_file_name=fin_go\
    proto/*.proto
	statik -src=./doc/swagger -dest=./doc

evans:
	evans --host localhost --port 9090 -r repl

.PHONY: postgres createdb dropdb migrateup migratedown sqlc test mock proto evans new_migration

# to run sqlc on windows - docker run --rm -v "D:\Development\Go\Golang Backend Course\golang-simple-bank:/src" -w /src sqlc/sqlc generate