postgres:
	docker run --name postgres16 -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres
createdb:
	docker exec -it postgres16 createdb --username=root --owner=root simplebank
dropdb:
	docker exec -it postgres16 dropdb simplebank
migrateup:
	migrate -path ./db/migration -database "postgresql://root:secret@localhost:5432/simplebank?sslmode=disable" -verbose up
migratedown:
	migrate -path ./db/migration -database "postgresql://root:secret@localhost:5432/simplebank?sslmode=disable" -verbose down
sqlc:
	sqlc generate
test:
	go test -v -cover ./...
mock:
	mockgen -destination db/mock/store.go example.com/simplebank/db/sqlc Store

.PHONY: postgres createdb dropdb migrateup migratedown sqlc test mock

# to run sqlc on windows - docker run --rm -v "D:\Development\Go\Golang Backend Course\golang-simple-bank:/src" -w /src sqlc/sqlc generate