// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package simplebank

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteAccountById(ctx context.Context, id int64) error
	DeleteEntryById(ctx context.Context, id int64) error
	DeleteTransferById(ctx context.Context, id int64) error
	GetAccountsCount(ctx context.Context) (int64, error)
	GetAcountById(ctx context.Context, id int64) (Account, error)
	GetAcountForUpdate(ctx context.Context, id int64) (Account, error)
	GetAllAccounts(ctx context.Context, arg GetAllAccountsParams) ([]Account, error)
	GetAllEntries(ctx context.Context, arg GetAllEntriesParams) ([]Entry, error)
	GetAllTransfers(ctx context.Context) ([]Transfer, error)
	GetEntryById(ctx context.Context, id int64) (Entry, error)
	GetTransferById(ctx context.Context, id int64) (Transfer, error)
	GetTransfersByFromAccountId(ctx context.Context, fromAccountID int64) ([]Transfer, error)
	GetTransfersByFromAccountIdAndToAccountId(ctx context.Context, arg GetTransfersByFromAccountIdAndToAccountIdParams) ([]Transfer, error)
	GetTransfersByToAccountId(ctx context.Context, toAccountID int64) ([]Transfer, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateEntryAmount(ctx context.Context, arg UpdateEntryAmountParams) error
}

var _ Querier = (*Queries)(nil)
